### PR TITLE
scripts: Add script for generating heat map visualizations of cyclic group captures

### PR DESCRIPTION
**Pull request by tomtseng**
Adds script for generating heat map visualizations of adversaries' cyclic group shapes. 

Maybe belongs in KataGoVisualizer, except we need to use `go_attack.go.Game` to simulate each game and find the cyclic capture.

Experiment page: https://www.notion.so/chaiberkeley/heat-map-visualizations-of-cyclic-adversaries-e6604589c2364aa1803b2f1738f0547d?pvs=4

### CODE REVIEW

**Comment by tomtseng** [comment]
lint is failing due to `black` being updated and failing on files not modified in this PR. Fix: PR #134

**Review by ed1d1a8d — CHANGES_REQUESTED** [review]
Perhaps you could add a link to an experiment log to show how to run this script?

**Comment by tomtseng** [comment]
Added to PR description: https://www.notion.so/chaiberkeley/heat-map-visualizations-of-cyclic-adversaries-e6604589c2364aa1803b2f1738f0547d?pvs=4

**Review by ed1d1a8d — APPROVED** [review]
Thanks for linking the experiment-log!
Looks good to me. We should discuss at some point whether we are going to include this style of analysis in the paper.

**Comment by tomtseng** [comment]
Closing because it's been moved to a notebook in https://github.com/AlignmentResearch/KataGoVisualizer/pull/98

**Pull request closed without merging**
